### PR TITLE
Rewrite comparison logic

### LINKED ISSUE #1: Incorrect handling of .post0 modifiers in comparisons
Well, this is rather nitpicky :-)

According to PEP 440:

> The post-release segment consists of the string .post, followed by a non-negative integer value. Post-releases are ordered by their numerical component, immediately following the corresponding release

"non-negative integer" means that `.post0` is a valid post-release segment. And since it's a post-release segment, it should be ordered after the corresponding release. This also matches the behavior of `packaging`:

```python
>>> from packaging.version import Version                                             
>>> Version("1.0") == Version("1.0.post0")                                            
False
>>> Version("1.0") < Version("1.0.post0")                                             
True
```

However, the code in this crate treats those two versions as identical for purposes of comparison: `==` returns True, `<` returns False.

I believe the bug is here:

https://github.com/relrod/pep440-rs/blob/f031645e4ccec11f342fe3f593a41cfaf8402ee5/src/lib.rs#L443

`post: None` and `post: Some(0)` both get mapped to `0` for comparison purposes.

(Discovered this because I was messing with using https://crates.io/crates/pubgrub to resolve python package versions, and that algorithm wants to be able to represent version constraints as ranges. So `== 1.0` compiles down to the range `[1.0, 1.0post0)`.)

### LINKED ISSUE #2: Incorrect handling of trailing zeros in comparisons
Quoth PEP 440:

> X.Y and X.Y.0 are not considered distinct release numbers, as the release segment comparison rules implicit expand the two component form to X.Y.0 when comparing it to any release segment that includes three components.

Unfortunately, this code acts differently:

```rust
use pep440::Version;

fn main() {
    let v1 = Version::parse("1.0").unwrap();
    let v2 = Version::parse("1.0.0").unwrap();

    println!("{}", v1 == v2);   // false  (should be true)
    println!("{}", v1 != v2);   // true   (should be false)
    println!("{}", v1 < v2);    // false  (correct)
    println!("{}", v1 <= v2);   // true   (correct)
    println!("{}", v1 > v2);    // false  (correct)
    println!("{}", v1 >= v2);   // true   (correct)
}
```

Note that this doesn't even define a consistent ordering -- the two versions are `<=` and `>=`, which should imply that they're `==`... but they aren't.

I also noticed that `normalize()` doesn't convert these into the same form... which I think might actually be correct? I'm only like 90% sure. But it does mean that I can't use `normalize()` to implement a version of `Hash` that agrees with `Eq`, so now I'm not sure how to make versions hashable.

### PR DESCRIPTION
**Pull request by njsmith**
- Comparison logic is now simpler and more correct (fixes #1, fixes #2)
  - Because it's stolen directly from 'packaging'
- impl Hash for Version
- More thorough tests to verify all of the above

### CODE REVIEW

**Comment by relrod** [comment]
(Closing and re-opening to try and kick CI)

**Comment by relrod** [comment]
CI failure is unrelated (I need to move the docs deployment out to a separate GHA workflow).

@njsmith I sent you an invite to give you direct commit access to the repo. I really appreciate your work on this, this PR looks great to me. If you make a crates.io account, I am happy to give you access to upload there too. Otherwise, I can try and cut a new version with this soon.

Thanks again!

**Comment by njsmith** [comment]
Thanks! I accepted the invite, and I just made a crates.io account... haven't tried doing anything with that before, so it might be fun :-) (how confidence inspiring is that?)

**Comment by relrod** [comment]
Well, this project was basically my first Rust project and was a bit of a playground to learn syntax and how things work, so there wasn't much confidence in the project to begin with 😉. I didn't really expect it to get much/any use. But if you find it useful and are able to hack on it, I don't want to get in your way :)

So basically: Have fun! I sent you an invite for crates.io now too :)

**Comment by njsmith** [comment]
ok, v0.2.0 is tagged and released :-)

**Pull request merged**
